Feature/#41 automatizar despliegue heroku
Full-Tortuga/decide-full-tortuga-admin pull request #55
Opened 2021-12-28 19:23 UTC by pedalopon

# Changes
- Se ha cambiado el archivo django.yml para que cada vez que se haga push de main o develop se despliegue en heroku

2021-12-28 21:18 UTC, JSnow11 approved these changes
- el workflow para hacer deploy funciona correctamente
-  hay un error en un check del frontend debido a que se ha pasado por alto en una PR anterior, esta es correcta
- la carpeta build solo se subirá cuando se realice una release, los desarrolladores no deben commitearla en ninguna rama "feature" o "fix"

2021-12-29 13:36 UTC, JSnow11 requested changes
Se deben crear 2 aplicaciones de heroku, 
- solo se debe pushear a la app de producción cuando se pushee a main/master.
- se debe pushear a la app de test cuando se pushee a develop

@pedalopon

2021-12-31 01:40 UTC, JSnow11 reviewed
Todo correcto, queda pendiente discutir si el credencial del correo debería convertirse en un secret de github

2021-12-31 01:40 UTC, JSnow11 commented on .github/workflows/herokuDevelop.yml
> +            heroku_email: "pedropontiga@gmail.com"
quiza debería ser un secret, en los requisitos se comenta que no deben haber credenciales expuestos en el repo

@pedalopon

2021-12-31 12:05 UTC, pedalopon commented on .github/workflows/herokuDevelop.yml
> +            heroku_email: "pedropontiga@gmail.com"
En la wiki de la asignatura solo comentan que se use un secret de github para la api key, pero supongo que se podría usar también para el correo

2021-12-31 12:31 UTC, JSnow11 approved these changes
Todo correcto

2021-12-31 12:31 UTC, merged