Feature/#16 api utils
Full-Tortuga/decide-full-tortuga-admin pull request #60
Opened 2022-01-03 19:58 UTC by ferrabled

Add Question, Voting and Census API Utils

2022-01-03 20:07 UTC, JSnow11 requested changes
hay parámetros que no son necesarios, se puede poner el valor (pe: "start" directamente en el body de la petición)

2022-01-03 20:07 UTC, JSnow11 commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        actionV: "stop",
este parámetro no es necesario, puedes poner "stop" directamente abajo, y ahorrarte el parámetro de la función

2022-01-03 20:07 UTC, JSnow11 commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        action: actionV,
este parámetro no es necesario

2022-01-03 20:07 UTC, JSnow11 commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        action: actionV,
no es necesario

2022-01-03 20:07 UTC, JSnow11 commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        action: actionV,
no es necesario

2022-01-04 10:48 UTC, ferrabled commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        actionV: "stop",
Cambiado en todos las funciones del mismo tipo para que devuelva la acción directamente

2022-01-04 10:48 UTC, ferrabled commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        action: actionV,
Arreglado

2022-01-04 10:49 UTC, ferrabled commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        action: actionV,
Eliminado el parámetro

2022-01-04 10:49 UTC, ferrabled commented on decide/administration/frontend/src/api/votingApiUtils.ts
> +        action: actionV,
El parámetro se devuelve directamente con su valor

2022-01-04 11:05 UTC, JSnow11 approved these changes
Looking fine, approved!

2022-01-04 11:05 UTC, merged