#6-feat:Added user CRUD operations
Full-Tortuga/decide-full-tortuga-admin pull request #7
Opened 2021-11-29 19:17 UTC by pedalopon

2021-12-03 18:46 UTC, josaloroc approved these changes
Revisado el código y testeadas cada una de las posibles peticiones descritas en la issue.

2021-12-04 15:06 UTC, JSnow11 commented
## Review
- Estaría bien añadir un endpoint auth aunque luego se redireccione la petición al endpoint por defecto de django, pe: `/administration/api/auth`, pudiendo hacer login ahí
- Quedan pendientes los middlewares para evitar comprobar el header en cada método
-

2021-12-04 15:08 UTC, JSnow11 requested changes
## Review
- [x] Estaría bien añadir un endpoint auth aunque luego se redireccione la petición al endpoint por defecto de django, pe: `/administration/api/auth`, pudiendo hacer login ahí
- [x] Quedan pendientes los middlewares para evitar comprobar el header en cada método
- [x] Estaría bien refactorizar y clarificar el funcionamiento de los endpoint, evitando tantos niveles de indentación cuando sea posible
- [x] Estaría bien investigar y documentar si swagger esta accesible por defecto, aparece como una dependencia en la configuración de django

2021-12-05 16:47 UTC, josaloroc approved these changes
Auth Login y Auth Logout funcionan correctamente. 
Se ha vuelto a comprobar el funcionamiento de los anteriores endpoints: todo correcto.

2021-12-06 20:10 UTC, JSnow11 approved these changes
## review
- todo correcto como primera versión funcional
- recomiendo buscar "best practices" para la localización y estructura de las clases de API

2021-12-07 12:02 UTC, merged